  
  
### Listado programas activos
GET  http://localhost:8080/getprogramas  HTTP/1.1

### Listado programas por Emplid
GET  http://localhost:8080/getprogramasbyemplid?Emplid=0000000081 HTTP/1.1

### Listado docentes
GET  http://localhost:8080/getdocentes HTTP/1.1

### Listado materias actuales
GET  http://localhost:8080/getmaterias HTTP/1.1

### Listado materias actuales
GET  http://localhost:8080/getautenticacion HTTP/1.1

### Listado estudiantes actuales
GET  http://localhost:8080/getestudiantes HTTP/1.1
### Listado estudiantes actuales
GET  http://localhost:8080/getestudiantebyemail?Email=gustavosantosr@gmail.com HTTP/1.1
### Listado materias por Emplid
GET  http://localhost:8080/getmateriasbyemplid?Emplid=0000000014 HTTP/1.1

### listado de materias por emplid y programa en nodos

GET  http://localhost:8080/getmateriasbyemplid?Emplid=0000000014&CodProg=206 HTTP/1.1

### horarios por Emplid
GET  http://localhost:8080/gethorariosbyemplid?Emplid=0000000014 HTTP/1.1

